In [1]:
# !wget -O raw_2016.csv -nc "http://www.belpa.be/pub/belpa.csv?piv_naam=&pin_begr_jr=&piv_postcode=&piv_gemeente=&piv_subtype_bedrag=&piv_type_bedrag=&pin_ondergrens=&pin_bovengrens=&pin_pagesize=10&pin_page_start=1&piv_sort=sort_webnaam&pin_sort_dir=0&piv_lng=EN&pin_inprod=1"

--2018-01-16 18:59:05--  http://www.belpa.be/pub/belpa.csv?piv_naam=&pin_begr_jr=&piv_postcode=&piv_gemeente=&piv_subtype_bedrag=&piv_type_bedrag=&pin_ondergrens=&pin_bovengrens=&pin_pagesize=10&pin_page_start=1&piv_sort=sort_webnaam&pin_sort_dir=0&piv_lng=EN&pin_inprod=1
Resolving www.belpa.be... 195.244.170.200
Connecting to www.belpa.be|195.244.170.200|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/vnd.ms-excel]
Saving to: ‘raw_2016.csv’

raw_2016.csv            [          <=>       ]  47.00M   389KB/s    in 71s

2018-01-16 19:00:46 (675 KB/s) - ‘raw_2016.csv’ saved [49279680]

In [1]:
!wget -O raw_2017.csv -nc "http://www.belpa.be/pub/belpa.csv?piv_naam=&pin_begr_jr=&piv_postcode=&piv_gemeente=&piv_subtype_bedrag=&piv_type_bedrag=&pin_ondergrens=&pin_bovengrens=&pin_pagesize=10&pin_page_start=1&piv_sort=sort_webnaam&pin_sort_dir=0&piv_lng=EN&pin_inprod=1"

--2018-06-16 13:06:33--  http://www.belpa.be/pub/belpa.csv?piv_naam=&pin_begr_jr=&piv_postcode=&piv_gemeente=&piv_subtype_bedrag=&piv_type_bedrag=&pin_ondergrens=&pin_bovengrens=&pin_pagesize=10&pin_page_start=1&piv_sort=sort_webnaam&pin_sort_dir=0&piv_lng=EN&pin_inprod=1
Resolving www.belpa.be (www.belpa.be)... 195.244.170.200
Connecting to www.belpa.be (www.belpa.be)|195.244.170.200|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/vnd.ms-excel]
Saving to: ‘raw_2017.csv’

raw_2017.csv            [                <=> ]  45.04M  2.61MB/s    in 17s

2018-06-16 13:07:08 (2.62 MB/s) - ‘raw_2017.csv’ saved [47231265]

In [ ]:
!wget -O raw_2018.csv -nc "http://www.belpa.be/pub/belpa.csv?piv_naam=&pin_begr_jr=&piv_postcode=&piv_gemeente=&piv_subtype_bedrag=&piv_type_bedrag=&pin_ondergrens=&pin_bovengrens=&pin_pagesize=10&pin_page_start=1&piv_sort=sort_webnaam&pin_sort_dir=0&piv_lng=EN&pin_inprod=1"

In [3]:
YEAR = 2018

In [1]:
import pandas as pd
from slugify import slugify

SyntaxError: invalid syntax (101655267.py, line 2)

In [5]:
df_raw = pd.read_csv('raw_{}.csv'.format(YEAR), delimiter=';', encoding='utf-8')
df_raw.head()

,name,postal_code,municipality,eagf,eafr,total,year,I.1,I.2,I.3,...,V/B.4.2,V/B.4.3,V/B.4.4,V/B.4.5,V/B.4.6,V/B.4.7,VI/A.1,VI/B.1,VI/C.1,VI/D.1
0,"""FERBOM"" SPRL",5020,Namur,"16.111,45","0,00","16.111,45",2017,"0,00","0,00","0,00",...,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00"
1,"SAGR ALAIN VERCRUYSSE ""FERME BOIS-LE-COMTE S. ...",7133,Binche,"38.658,44","0,00","38.658,44",2017,"0,00","0,00","0,00",...,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00"
2,"SAGR DECOENE ""FERME DU MONT GARNI"" S. AGR.",7331,Saint-Ghislain,"15.155,04","4.309,20","19.464,24",2017,"0,00","0,00","0,00",...,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00"
3,"SAGR DEGALLAIX ""FERME DE LA BARRIERE"" S. AGR.",7501,Tournai,"18.137,95","0,00","18.137,95",2017,"0,00","0,00","0,00",...,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00"
4,"SAGR DELFOSSE ""FERME DE BARGETTE"" S. AGR.",7387,Honnelles,"25.163,31","918,00","26.081,31",2017,"0,00","0,00","0,00",...,"0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00","0,00"

In [6]:
id_vars = 'name	postal_code	municipality	eagf	eafr	total	year'.split('\t')
all_columns = list(df_raw.columns)
total_cols = ['total', 'eafr', 'eagf']
value_vars = list(set(all_columns) - set(id_vars))

In [7]:
def fix_nums(series):
    return series.astype(str).str.replace('.', '').str.replace(',', '.')

for val in value_vars + total_cols:
    df_raw[val] = pd.to_numeric(fix_nums(df_raw[val]), errors='coerce')
    
df_raw.head()

,name,postal_code,municipality,eagf,eafr,total,year,I.1,I.2,I.3,...,V/B.4.2,V/B.4.3,V/B.4.4,V/B.4.5,V/B.4.6,V/B.4.7,VI/A.1,VI/B.1,VI/C.1,VI/D.1
0,"""FERBOM"" SPRL",5020,Namur,16111.45,0.0,16111.45,2017,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,"SAGR ALAIN VERCRUYSSE ""FERME BOIS-LE-COMTE S. ...",7133,Binche,38658.44,0.0,38658.44,2017,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,"SAGR DECOENE ""FERME DU MONT GARNI"" S. AGR.",7331,Saint-Ghislain,15155.04,4309.2,19464.24,2017,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,"SAGR DEGALLAIX ""FERME DE LA BARRIERE"" S. AGR.",7501,Tournai,18137.95,0.0,18137.95,2017,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,"SAGR DELFOSSE ""FERME DE BARGETTE"" S. AGR.",7387,Honnelles,25163.31,918.0,26081.31,2017,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df = pd.melt(df_raw, id_vars=id_vars, value_vars=value_vars, value_name='amount', var_name='scheme')
df = df[df['amount'] > 0]
df = df.drop(total_cols, 1)
df.head()

,name,postal_code,municipality,year,scheme,amount
2,"SAGR DECOENE ""FERME DU MONT GARNI"" S. AGR.",7331,Saint-Ghislain,2017,IV/A.15,4309.2
4,"SAGR DELFOSSE ""FERME DE BARGETTE"" S. AGR.",7387,Honnelles,2017,IV/A.15,432.0
5,"SAGR DOTREMONT DE DANSONSPENNE ""AGRIDANS"" S. AGR.",6567,Merbes-le-Château,2017,IV/A.15,1800.0
6,"SAGR DUBOIS J &P ""FERME DU PREAU"" S. AGR.",7321,Bernissart,2017,IV/A.15,15170.7
12,"SAGR WIEME ERIC ""FERME DE BETAUMONT"" S. AGR.",5170,Profondeville,2017,IV/A.15,267.4

In [9]:
df = df.rename(columns={
    'name': 'recipient_name',
    'postal_code': 'recipient_postcode',
    'municipality': 'recipient_location',
})
df['currency'] = 'EUR'
df['country'] = 'BE'

def generate_id(row):
    return u'BE-%s' % slugify(row['recipient_name'], row['recipient_postcode'], row['recipient_name'])

df['recipient_id'] = df.apply(generate_id, 1)
df.head()

,recipient_name,recipient_postcode,recipient_location,year,scheme,amount,currency,country,recipient_id
2,"SAGR DECOENE ""FERME DU MONT GARNI"" S. AGR.",7331,Saint-Ghislain,2017,IV/A.15,4309.2,EUR,BE,"BE-7331-SAGR DECOENE ""FERME DU MONT GARNI"" S. ..."
4,"SAGR DELFOSSE ""FERME DE BARGETTE"" S. AGR.",7387,Honnelles,2017,IV/A.15,432.0,EUR,BE,"BE-7387-SAGR DELFOSSE ""FERME DE BARGETTE"" S. AGR."
5,"SAGR DOTREMONT DE DANSONSPENNE ""AGRIDANS"" S. AGR.",6567,Merbes-le-Château,2017,IV/A.15,1800.0,EUR,BE,"BE-6567-SAGR DOTREMONT DE DANSONSPENNE ""AGRIDA..."
6,"SAGR DUBOIS J &P ""FERME DU PREAU"" S. AGR.",7321,Bernissart,2017,IV/A.15,15170.7,EUR,BE,"BE-7321-SAGR DUBOIS J &P ""FERME DU PREAU"" S. AGR."
12,"SAGR WIEME ERIC ""FERME DE BETAUMONT"" S. AGR.",5170,Profondeville,2017,IV/A.15,267.4,EUR,BE,"BE-5170-SAGR WIEME ERIC ""FERME DE BETAUMONT"" S..."

In [10]:
df.year.value_counts()

2017    162532
2016    148392
Name: year, dtype: int64

In [11]:
df[df['year'] == YEAR].to_csv('be_{}.csv.gz'.format(YEAR), index=False, encoding='utf-8', compression='gzip')